#!/bin/bash
set -e

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS user_db;
    CREATE DATABASE IF NOT EXISTS notification_db;

    CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
    CREATE USER IF NOT EXISTS '${NOTIFICATION_MYSQL_USER}'@'%' IDENTIFIED BY '${NOTIFICATION_MYSQL_PASSWORD}';

    GRANT ALL PRIVILEGES ON user_db.* TO '${MYSQL_USER}'@'%';
    GRANT ALL PRIVILEGES ON notification_db.* TO '${NOTIFICATION_MYSQL_USER}'@'%';

    FLUSH PRIVILEGES;
EOSQL
